[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyprime"
version = "1.0.0"
description = "A Python package for pyprime scientific analysis tools."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "Paul Dräger", email = "paul_ansgar.draeger@mailbox.tu-dresden.de" },
]

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
include = ["pyprime*"]
