[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyprime"
version = "1.0.0"
description = "A Python package for pyprime scientific analysis tools."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "PyPrime Authors", email = "info@example.com" },
]
dependencies = [
  "AMP==1.1.4",
  "matplotlib==3.10.8",
  "numpy==2.4.4",
  "pandas==3.0.2",
  "paramiko==3.5.0",
  "paths==0.0.1a1",
  "plot==0.6.5",
  "pyvista==0.45.0",
  "pyvoro==1.3.2",
  "scipy==1.17.1",
  "scp==0.14.1",
  "Shapely==2.1.2",
  "sympy==1.13.2",
  "tqdm==4.67.1",
]

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
include = ["pyprime*"]
